import string

better_wording = {
            "byzantine empire": "eastern roman empire",
            "enlightenment": "reason, individualism movement",
            "fauvism": "bold color art",
            "quantum entanglement": "particle connection phenomenon",
            "hubble's law": "universe expansion observation",
            "mendelian inheritance": "genetics, mendel's laws",
            "krebs cycle": "cellular respiration process",
            "psychoanalysis": "freud, mind theory",
            "behaviorism": "observable behavior psychology",
            "cognitive dissonance": "mental conflict theory",
            "tectonic plates": "earth crust pieces",
            "mesozoic era": "dinosaurs, age",
            "industrial design": "object design process",
            "minimalism": "simplicity art movement",
            "pop art": "cultural imagery art",
            "existential crisis": "life meaning question",
            "social darwinism": "survival, societal application",
            "quantum computing": "superposition, computing tech",
            "sustainable development": "future, needs meeting",
            "gene therapy": "dna treatment technique",
            "renaissance humanism": "classical learning revival",
            "baroque music": "1600-1750 music style",
            "classicism": "greek, roman inspiration",
            "neo-classicism": "classical revival movement",
            "gothic novel": "horror, romance genre",
            "romanticism": "emotion, nature emphasis",
            "dystopian literature": "dark, future genre",
            "stream of consciousness": "thoughts, literary style",
            "bioluminescence": "living light emission",
            "dark matter": "invisible mass theory",
            "game theory": "strategic interaction study",
            "heisenberg uncertainty principle": "measurement, quantum limit",
            "photovoltaic effect": "solar power conversion",
            "fermi paradox": "aliens, absence question",
            "carbon footprint": "emissions, personal impact",
            "blockchain": "distributed ledger technology",
            "virtual reality": "immersive digital world",
            "augmented reality": "enhanced real-world overlay",
            "crispr": "gene editing technology",
            "deep learning": "ai, neural networks",
            "internet of things": "connected device network",
            "big data": "large, complex datasets",
            "machine learning": "ai, learning algorithms",
            "smart contracts": "blockchain, automated agreements",
            "cryptocurrency": "digital, encrypted currency",
            "sustainable agriculture": "eco-friendly farming",
            "renewable energy": "sustainable energy sources",
            "conservation biology": "biodiversity, protection science",
            "urban planning": "city development, management",
            "digital nomad": "remote work lifestyle",
            "minimalism lifestyle": "simplicity, living philosophy",
            "circular economy": "reuse, sustainability model",
            "remote sensing": "distance, information gathering",
            "3d printing": "additive manufacturing process",
            "nanomaterials": "ultra-small materials science",
            "quantum dots": "semiconductor nanocrystals",
            "synthetic biology": "engineering, biology fusion",
            "personal genomics": "dna, individual analysis",
            "wearable technology": "smart, wearable devices",
            "green technology": "environmental tech solutions",
            "biofuel": "biomass energy source",
            "hydroponics": "soilless plant cultivation",
            "aeroponics": "air, mist cultivation",
            "virtual collaboration": "online teamwork technology",
            "cybersecurity": "information protection tech",
            "artificial photosynthesis": "solar energy, water splitting",
            "smart grid": "electricity network tech",
            "nuclear fusion": "energy, atomic reaction",
            "space elevator": "proposed, orbit transport",
            "terraforming": "planet habitat altering",
            "exoplanets": "planets beyond solar",
            "dark energy": "universe expansion force",
            "multiverse theory": "multiple universes concept",
            "neuroplasticity": "brain, change ability",
            "cryonics": "low temp, body preservation",
            "sociobiology": "biology, social behavior",
            "anthropocene": "human impact epoch",
            "biodegradable": "decompose, natural process",
            "geoengineering": "climate, intentional intervention",
            "permaculture": "sustainable, agriculture design",
            "ecotourism": "conservation, travel focus",
            "microplastics": "small, plastic particles",
            "biodiversity": "biological variety, ecosystems",
            "invasive species": "non-native, ecosystem harm",
            "carbon sequestration": "co2, storage method",
            "afforestation": "planting trees, land",
            "desalination": "salt, water removal",
            "aquaculture": "water, organism farming",
            "agroforestry": "trees, crops integration",
            "sustainable fishing": "fish stocks, maintaining",
            "green building": "eco-friendly construction",
            "passive solar": "building",
            "composting": "organic matter, decay",
            "zero waste": "waste, minimal lifestyle",
            "food security": "reliable, food access",
            "urban farming": "city, agriculture practice",
            "precision agriculture": "tech, farming optimization",
            "clean coal": "emissions, reduction tech",
            "smart cities": "technology, urban management",
            "digital detox": "tech, usage break",
            "slow food": "local, food movement",
            "telemedicine": "remote, medical services",
            "pandemic": "plague",
            "e-health": "health services, electrofnic",
            "m-health": "mobile, health tech",
            "teletherapy": "remote, therapy services",
            "e-learning": "learning, electronic means",
            "digital literacy": "digital technology, competency",
            "cyber-physical systems": "control, physical processes",
            "virtual teams": "remote, work groups",
            "crowdsourcing": "task, public contribution",
            "crowdfunding": "funding, public contribution",
            "e-commerce": "online, commerce activities",
            "social media": "digital, communication platforms",
            "digital rights management": "content, access control",
            "open source": "code, public access",
            "cloud computing": "internet-based computing services",
            "data mining": "big data, pattern analysis",
            "natural language processing": "computers, human language",
            "computer vision": "machines, visual understanding",
            "augmented intelligence": "ai, human enhancement",
            "predictive analytics": "data, future prediction",
            "edge computing": "data, local processing",
            "quantum cryptography": "quantum, secure communication",
            "robotics": "automated, machines design",
            "autonomous vehicles": "self-driving, technology",
            "internet privacy": "online, information protection",
            "digital footprint": "online, data trace",
            "biometrics": "body, identification tech",
            "facial recognition": "identify, facial features",
            "voice assistant": "ai, voice command",
            "smart home": "automated, home technology",
            "internet censorship": "online, content control",
            "digital currency": "electronic, money form",
            "fintech": "financial, technology services",
            "insurtech": "insurance, technology innovation",
            "regtech": "regulatory, technology compliance",
            "bitcoin": "cryptocurrency, digital currency",
            "ethereum": "blockchain, smart contracts",
            "nft": "non-fungible, token",
            "decentralized finance": "finance, blockchain tech",
            "tokenization": "asset, digital representation",
            "defi": "decentralized, financial services",
            "metaverse": "virtual, reality universe",
            "web3": "decentralized, web version",
            "dao": "decentralized, autonomous organization",
            "dapp": "decentralized, application",
            "ipfs": "peer-to-peer, file system",
            "solidity": "ethereum, programming language",
            "chainlink": "decentralized, oracle network",
            "polkadot": "blockchain, interoperability protocol",
            "cardano": "blockchain, proof-of-stake",
            "solana": "high-performance, blockchain",
            "nft art": "digital, art token",
            "crypto art": "art, cryptocurrency transaction",
            "digital collectible": "collectible, digital form",
            "virtual real estate": "property, virtual world",
            "digital twin": "virtual, real-world replica",
            "ai art": "art, ai creation",
            "generative art": "algorithm, art creation",
            "vr gaming": "gaming, virtual reality",
            "ar gaming": "gaming, augmented reality",
            "esports": "competitive, video gaming",
            "mobile gaming": "gaming, mobile devices",
            "cloud gaming": "streaming, video games",
            "game streaming": "live, game broadcasting",
            "indie games": "independent, video games",
            "game development": "video game, creation",
            "unity engine": "game development, engine",
            "unreal engine": "3d, creation tool",
            "game design": "game, creation process",
            "level design": "game, level creation",
            "game mechanics": "gameplay, rules system",
            "narrative design": "story, game integration",
            "game monetization": "game, revenue generation",
            "loot box": "game, item purchase",
            "microtransaction": "small, digital purchase",
            "free-to-play": "game, free access",
            "pay-to-win": "advantage, payment required",
            "mmorpg": "online, multiplayer game",
            "battle royale": "survival, game genre",
            "first-person shooter": "shooter, first-person perspective",
            "real-time strategy": "strategy, real-time game",
            "turn-based strategy": "strategy, turn-based game",
            "puzzle game": "game, puzzle solving",
            "simulation game": "life, simulation game",
            "sports game": "sports, video game",
            "racing game": "racing, video game",
            "fighting game": "combat, video game",
            "platformer game": "jumping, platform game",
            "adventure game": "story, exploration game",
            "role-playing game": "character, role game",
            "sandbox game": "open-world, creativity game",
            "horror game": "scary, video game",
            "stealth game": "sneaking, strategy game",
            "survival game": "survival, resource game",
            "music game": "rhythm, music game",
            "educational game": "learning, video game",
            "trivia game": "questions, knowledge game",
            "casual game": "simple, easy game",
            "hyper-casual game": "very simple, quick game",
            "mobile app": "smartphone, software application",
            "app development": "mobile software, creation",
            "ios": "apple, operating system",
            "android": "google, operating system",
            "cross-platform": "multiple, os compatibility",
            "user interface": "system, user interaction",
            "user experience": "user, interaction design",
            "front-end": "web, client-side",
            "back-end": "server, database side",
            "full-stack": "front, back-end development",
            "web development": "website, creation process",
            "responsive design": "screen, adaptable layout",
            "mobile-first design": "mobile, priority design",
            "api": "application, programming interface",
            "database": "data, organized storage",
            "sql": "structured, query language",
            "nosql": "non-relational, database",
            "cloud storage": "internet, data storage",
            "data analysis": "data, examination process",
            "data visualization": "visual, data representation",
            "business intelligence": "data, business insights",
            "artificial intelligence": "ai",
            "mixed reality": "virtual, real blend",
            "encryption": "data, security method",
            "firewall": "network, security system",
            "malware": "malicious, software",
            "phishing": "fraudulent, communication scam",
            "vpn": "private, network access",
            "antivirus": "malware, protection software",
            "data breach": "data, unauthorized access",
            "ransomware": "malware, payment demand",
            "identity theft": "personal, information theft",
            "two-factor authentication": "security, verification method",
            "digital privacy": "online, privacy protection",
            "data encryption": "data, encoding process",
            "secure socket layer": "web, security protocol",
            "public key infrastructure": "digital, certificate system",
            "fingerprint scanner": "biometric, identification device",
            "voice recognition": "voice, identification tech",
            "digital signature": "electronic, signature verification",
            "cyber warfare": "internet, conflict engagement",
            "ethical hacking": "security, vulnerability testing",
            "penetration testing": "system, security evaluation",
            "social engineering": "manipulation, information extraction",
            "information security": "data, protection measures",
            "network security": "networks, protection measures",
            "application security": "apps, protection measures",
            "cloud security": "cloud, protection measures",
            "operational security": "processes, protection measures",
            "internet safety": "online, safety practices",
            "digital citizenship": "responsible, technology use",
            "cyberbullying": "online, harassment form",
            "digital wellness": "healthy, technology use",
            "screen time": "device, usage duration",
            "privacy settings": "personal, data control",
            "social media safety": "online, interaction safety",
            "password management": "secure, password practices",
            "online shopping safety": "e-commerce, security practices",
            "email security": "email, protection measures",
            "secure browsing": "safe, internet navigation",
            "mobile security": "smartphone, protection measures",
            "vpn usage": "private, network use",
            "antivirus software": "malware, protection program",
            "data backup": "data, copy storage",
            "software as a service": "software, cloud delivery",
            "platform as a service": "platform, cloud delivery",
            "infrastructure as a service": "infrastructure, cloud delivery",
            "public cloud": "open, cloud services",
            "private cloud": "exclusive, cloud services",
            "hybrid cloud": "mixed, cloud services",
            "virtualization": "virtual, resources creation",
            "data center": "data, storage facility",
            "server farm": "data, server collection",
            "network architecture": "network, design structure",
            "data management": "data, handling processes",
            "database administration": "database, management job",
            "data warehouse": "data, centralized storage",
            "etl": "extract, transform, load",
            "data governance": "data, management policy",
            "data privacy": "personal, data protection",
            "data security": "data, protection measures",
            "mona lisa": "leonardo da vinci",
            "starry night": "vincent van gogh",
            "last supper": "leonardo da vinci",
            "guernica": "pablo picasso",
            "persistence of memory": "salvador dalí",
            "scream": "edvard munch",
            "creation of adam": "michelangelo",
            "kiss": "gustav klimt",
            "water lilies": "claude monet",
            "great wave off kanagawa": "hokusai",
            "birth of venus": "sandro botticelli",
            "starry night over the rhône": "vincent van gogh",
            "night watch": "rembrandt",
            "thinker": "auguste rodin",
            "nighthawks": "edward hopper",
            "campbell's soup cans": "andy warhol",
            "the persistence of memory": "salvador dalí",
            "the birth of venus": "sandro botticelli",
            "the great wave off kanagawa": "hokusai",
            "les demoiselles d'avignon": "pablo picasso",
            "the starry night": "vincent van gogh",
            "girl with a pearl earring": "johannes vermeer",
            "the last supper": "leonardo da vinci",
            "american gothic": "grant wood",
            "the thinker": "auguste rodin",
            "whistler's mother": "james mcneill whistler",
            "father of the united states": "founder constitution",
            "declaration of independence": "United States",
            "communist manifesto": "Karl Marx and Friedrich Engels",
            "wealth of nations": "Adam Smith",
            "art of war": "Sun Tzu",
            "prince": "Niccolò Machiavelli",
            "common sense": "Thomas Paine",
            "das kapital": "Karl Marx",
            "1984": "George Orwell",
            "animal farm": "George Orwell",
            "pride and prejudice": "Jane Austen",
            "war and peace": "Leo Tolstoy",
            "crime and punishment": "Fyodor Dostoevsky",
            "odyssey": "Homer",
            "iliad": "Homer",
            "divine comedy": "Dante Alighieri",
            "don quixote": "Miguel de Cervantes",
            "hamlet": "William Shakespeare",
            "macbeth": "William Shakespeare",
            "romeo and juliet": "William Shakespeare",
            "canterbury tales": "Geoffrey Chaucer",
            "beowulf": "Unknown",
            "adventures of huckleberry finn": "Mark Twain",
            "adventures of tom sawyer": "Mark Twain",
            "frankenstein": "Mary Shelley",
            "dracula": "Bram Stoker",
            "moby-dick": "Herman Melville",
            "picture of dorian gray": "Oscar Wilde",
            "wuthering heights": "Emily Brontë",
            "jane eyre": "Charlotte Brontë",
            "scarlet letter": "Nathaniel Hawthorne",
            "sun also rises": "Ernest Hemingway",
            "one hundred years of solitude": "Gabriel García Márquez",
            "tale of two cities": "Charles Dickens",
            "les misérables": "Victor Hugo",
            "anna karenina": "Leo Tolstoy",
            "brothers karamazov": "Fyodor Dostoevsky",
            "sound and the fury": "William Faulkner",
            "harry potter series": "J.K. Rowling",
            "hunger games series": "Suzanne Collins",
            "divergent series": "Veronica Roth",
            "twilight series": "Stephenie Meyer",
            "da vinci code": "Dan Brown",
            "alchemist": "Paulo Coelho",
            "kite runner": "Khaled Hosseini",
            "thousand splendid suns": "Khaled Hosseini",
            "help": "Kathryn Stockett",
            "fault in our stars": "John Green",
            "gone girl": "Gillian Flynn",
            "girl with the dragon tattoo": "Stieg Larsson",
            "girl on the train": "Paula Hawkins",
            "educated": "Tara Westover",
            "becoming": "Michelle Obama",
            "subtle art of not giving a f*ck": "Mark Manson",
            "sapiens: a brief history of humankind": "Yuval Noah Harari",
            "power of now": "Eckhart Tolle",
            "thinking, fast and slow": "Daniel Kahneman",
            "7 habits of highly effective people": "Stephen R. Covey",
            "how to win friends and influence people": "Dale Carnegie",
            "quiet: power of introverts in a world that can't stop talking": "Susan Cain",
            "four agreements": "Don Miguel Ruiz",
            "man's search for meaning": "Viktor E. Frankl",
            "body keeps the score": "Bessel van der Kolk",
            "immortal life of henrietta lacks": "Rebecca Skloot",
            "just mercy": "Bryan Stevenson",
            "white fragility": "Robin DiAngelo",
            "born a crime": "Trevor Noah",
            "warmth of other suns": "Isabel Wilkerson",
            "between the world and me": "Ta-Nehisi Coates",
            "hillbilly elegy": "J.D. Vance",
            "braiding sweetgrass": "Robin Wall Kimmerer",
            "evicted": "Matthew Desmond",
            "stamped from the beginning": "Ibram X. Kendi",
            "new jim crow": "Michelle Alexander",
            "slaughterhouse-five": "Kurt Vonnegut",
            "catch-22": "Joseph Heller",
            "one flew over the cuckoo's nest": "Ken Kesey",
            "beloved": "Toni Morrison",
            "color purple": "Alice Walker",
            "invisible man": "Ralph Ellison",
            "bell jar": "Sylvia Plath",
            "mrs. dalloway": "Virginia Woolf",
            "their eyes were watching god": "Zora Neale Hurston",
            "native son": "Richard Wright",
            "grapes of wrath": "John Steinbeck",
            "on road": "Jack Kerouac",
            "old man and sea": "Ernest Hemingway",
            "in cold blood": "Truman Capote",
            "fear and loathing in las vegas": "Hunter S. Thompson",
            "hitchhiker's guide to the galaxy": "Douglas Adams",
            "catcher in the rye": "J.D. Salinger",
            "to kill a mockingbird": "Harper Lee",
            "great gatsby": "F. Scott Fitzgerald",
            "lord of the rings": "J.R.R. Tolkien",
            "hobbit": "J.R.R. Tolkien",
            "alice's adventures in wonderland": "Lewis Carroll",
            "through looking-glass": "Lewis Carroll",
            "chronicles of narnia": "C.S. Lewis",
            "lion, witch and wardrobe": "C.S. Lewis",
            "horse and his boy": "C.S. Lewis",
            "prince caspian": "C.S. Lewis",
            "voyage of dawn treader": "C.S. Lewis",
            "silver chair": "C.S. Lewis",
            "last battle": "C.S. Lewis",
            "harry potter and philosopher's stone": "J.K. Rowling",
            "harry potter and chamber of secrets": "J.K. Rowling",
            "harry potter and prisoner of azkaban": "J.K. Rowling",
            "harry potter and goblet of fire": "J.K. Rowling",
            "harry potter and order of phoenix": "J.K. Rowling",
            "3d": "3 Dimensional, Depth",
            "water cycle": "evaporation, condensation, Precipitation"
            }

class LLMImprove:
    @staticmethod
    def improve_query(query):
        # Initialize the results
        results = query
        # Convert the query to lowercase
        query = query.lower()

        # Remove punctuation
        query = query.translate(str.maketrans('', '', string.punctuation))

        # Split the query into words
        words = query.split()

        # Check if each format of the query is a dictionary
        for i in range(len(words)):
            for j in range(i + 1, len(words) + 1):
                subquery = ' '.join(words[i:j])
                if subquery in better_wording:
                    results += " " + better_wording[subquery]
                    return results

        return results

print(LLMImprove.improve_query("3D"))

